# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://janek.cz/"  # Include trailing slash
# title = ""  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright © 2022, Jan Vackar; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
# disqusShortname = ""

DefaultContentLanguage = "cz"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]